version: '3'

services: 
    bdd_users:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - "3306:3306"
        volumes:
            - ./bdd:/docker-entrypoint-initdb.d:ro
    
    web_services:
        build:
            context: ./web_services
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - '5000:5000'

    siteweb:
        build:
            context: ./web_app
            dockerfile: Dockerfile
        ports:
            - "80:80"